// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 商品信息
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 查询商品列表
type GetProductsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReq) Reset() {
	*x = GetProductsReq{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReq) ProtoMessage() {}

func (x *GetProductsReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReq.ProtoReflect.Descriptor instead.
func (*GetProductsReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProductsReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetProductsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数 用于前端确定分页页数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResp) Reset() {
	*x = GetProductsResp{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResp) ProtoMessage() {}

func (x *GetProductsResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResp.ProtoReflect.Descriptor instead.
func (*GetProductsResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductsResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetProductsResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 查询商品详情
type GetProductDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailReq) Reset() {
	*x = GetProductDetailReq{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailReq) ProtoMessage() {}

func (x *GetProductDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailReq.ProtoReflect.Descriptor instead.
func (*GetProductDetailReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductDetailReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductDetailResp) Reset() {
	*x = GetProductDetailResp{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductDetailResp) ProtoMessage() {}

func (x *GetProductDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductDetailResp.ProtoReflect.Descriptor instead.
func (*GetProductDetailResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductDetailResp) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

// 查询库存
type GetInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryReq) Reset() {
	*x = GetInventoryReq{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryReq) ProtoMessage() {}

func (x *GetInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryReq.ProtoReflect.Descriptor instead.
func (*GetInventoryReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetInventoryReq) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResp) Reset() {
	*x = GetInventoryResp{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResp) ProtoMessage() {}

func (x *GetInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResp.ProtoReflect.Descriptor instead.
func (*GetInventoryResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetInventoryResp) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetInventoryResp) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

// 添加商品
type CreateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReq) Reset() {
	*x = CreateProductReq{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReq) ProtoMessage() {}

func (x *CreateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReq.ProtoReflect.Descriptor instead.
func (*CreateProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type CreateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResp) Reset() {
	*x = CreateProductResp{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResp) ProtoMessage() {}

func (x *CreateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResp.ProtoReflect.Descriptor instead.
func (*CreateProductResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// 更新商品
type UpdateProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReq) Reset() {
	*x = UpdateProductReq{}
	mi := &file_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReq) ProtoMessage() {}

func (x *UpdateProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReq.ProtoReflect.Descriptor instead.
func (*UpdateProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateProductReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductReq) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResp) Reset() {
	*x = UpdateProductResp{}
	mi := &file_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResp) ProtoMessage() {}

func (x *UpdateProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResp.ProtoReflect.Descriptor instead.
func (*UpdateProductResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateProductResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// 删除商品
type DeleteProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReq) Reset() {
	*x = DeleteProductReq{}
	mi := &file_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReq) ProtoMessage() {}

func (x *DeleteProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReq.ProtoReflect.Descriptor instead.
func (*DeleteProductReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteProductReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResp) Reset() {
	*x = DeleteProductResp{}
	mi := &file_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResp) ProtoMessage() {}

func (x *DeleteProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResp.ProtoReflect.Descriptor instead.
func (*DeleteProductResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteProductResp) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

// 语义搜索
type SemanticSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchReq) Reset() {
	*x = SemanticSearchReq{}
	mi := &file_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchReq) ProtoMessage() {}

func (x *SemanticSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchReq.ProtoReflect.Descriptor instead.
func (*SemanticSearchReq) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *SemanticSearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SemanticSearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResp) Reset() {
	*x = SemanticSearchResp{}
	mi := &file_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResp) ProtoMessage() {}

func (x *SemanticSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResp.ProtoReflect.Descriptor instead.
func (*SemanticSearchResp) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *SemanticSearchResp) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\acatalog\"\x89\x01\n" +
	"\aProduct\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\"@\n" +
	"\x0eGetProductsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"U\n" +
	"\x0fGetProductsResp\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"3\n" +
	"\x13GetProductDetailReq\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\"B\n" +
	"\x14GetProductDetailResp\x12*\n" +
	"\aproduct\x18\x01 \x01(\v2\x10.catalog.ProductR\aproduct\"/\n" +
	"\x0fGetInventoryReq\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x05R\tproductId\"F\n" +
	"\x10GetInventoryResp\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x05R\tproductId\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"t\n" +
	"\x10CreateProductReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\"1\n" +
	"\x11CreateProductResp\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\"\x92\x01\n" +
	"\x10UpdateProductReq\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\"1\n" +
	"\x11UpdateProductResp\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\"0\n" +
	"\x10DeleteProductReq\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\"1\n" +
	"\x11DeleteProductResp\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x03R\tproductId\")\n" +
	"\x11SemanticSearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"B\n" +
	"\x12SemanticSearchResp\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts2\x84\x04\n" +
	"\aCatalog\x12@\n" +
	"\vGetProducts\x12\x17.catalog.GetProductsReq\x1a\x18.catalog.GetProductsResp\x12O\n" +
	"\x10GetProductDetail\x12\x1c.catalog.GetProductDetailReq\x1a\x1d.catalog.GetProductDetailResp\x12C\n" +
	"\fGetInventory\x12\x18.catalog.GetInventoryReq\x1a\x19.catalog.GetInventoryResp\x12F\n" +
	"\rCreateProduct\x12\x19.catalog.CreateProductReq\x1a\x1a.catalog.CreateProductResp\x12F\n" +
	"\rUpdateProduct\x12\x19.catalog.UpdateProductReq\x1a\x1a.catalog.UpdateProductResp\x12F\n" +
	"\rDeleteProduct\x12\x19.catalog.DeleteProductReq\x1a\x1a.catalog.DeleteProductResp\x12I\n" +
	"\x0eSemanticSearch\x12\x1a.catalog.SemanticSearchReq\x1a\x1b.catalog.SemanticSearchRespB\vZ\t./catalogb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_catalog_proto_goTypes = []any{
	(*Product)(nil),              // 0: catalog.Product
	(*GetProductsReq)(nil),       // 1: catalog.GetProductsReq
	(*GetProductsResp)(nil),      // 2: catalog.GetProductsResp
	(*GetProductDetailReq)(nil),  // 3: catalog.GetProductDetailReq
	(*GetProductDetailResp)(nil), // 4: catalog.GetProductDetailResp
	(*GetInventoryReq)(nil),      // 5: catalog.GetInventoryReq
	(*GetInventoryResp)(nil),     // 6: catalog.GetInventoryResp
	(*CreateProductReq)(nil),     // 7: catalog.CreateProductReq
	(*CreateProductResp)(nil),    // 8: catalog.CreateProductResp
	(*UpdateProductReq)(nil),     // 9: catalog.UpdateProductReq
	(*UpdateProductResp)(nil),    // 10: catalog.UpdateProductResp
	(*DeleteProductReq)(nil),     // 11: catalog.DeleteProductReq
	(*DeleteProductResp)(nil),    // 12: catalog.DeleteProductResp
	(*SemanticSearchReq)(nil),    // 13: catalog.SemanticSearchReq
	(*SemanticSearchResp)(nil),   // 14: catalog.SemanticSearchResp
}
var file_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.GetProductsResp.products:type_name -> catalog.Product
	0,  // 1: catalog.GetProductDetailResp.product:type_name -> catalog.Product
	0,  // 2: catalog.SemanticSearchResp.products:type_name -> catalog.Product
	1,  // 3: catalog.Catalog.GetProducts:input_type -> catalog.GetProductsReq
	3,  // 4: catalog.Catalog.GetProductDetail:input_type -> catalog.GetProductDetailReq
	5,  // 5: catalog.Catalog.GetInventory:input_type -> catalog.GetInventoryReq
	7,  // 6: catalog.Catalog.CreateProduct:input_type -> catalog.CreateProductReq
	9,  // 7: catalog.Catalog.UpdateProduct:input_type -> catalog.UpdateProductReq
	11, // 8: catalog.Catalog.DeleteProduct:input_type -> catalog.DeleteProductReq
	13, // 9: catalog.Catalog.SemanticSearch:input_type -> catalog.SemanticSearchReq
	2,  // 10: catalog.Catalog.GetProducts:output_type -> catalog.GetProductsResp
	4,  // 11: catalog.Catalog.GetProductDetail:output_type -> catalog.GetProductDetailResp
	6,  // 12: catalog.Catalog.GetInventory:output_type -> catalog.GetInventoryResp
	8,  // 13: catalog.Catalog.CreateProduct:output_type -> catalog.CreateProductResp
	10, // 14: catalog.Catalog.UpdateProduct:output_type -> catalog.UpdateProductResp
	12, // 15: catalog.Catalog.DeleteProduct:output_type -> catalog.DeleteProductResp
	14, // 16: catalog.Catalog.SemanticSearch:output_type -> catalog.SemanticSearchResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
