// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type AddItemReq struct {
	ProductId   int32
	ProductName string
	Quantity    int32
	Price       float64
}

type DeleteItemReq struct {
	ProductId int32
}

type GetCartResp struct {
	Cart Cart
}

type UpdateItemReq struct {
	ProductId int32
	Quantity  int32
}
