// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CreateProductReq struct {
	Name        string
	Description string
	Price       float64
	Stock       int32
}

type CreateProductResp struct {
	ProductId int64
}

type DeleteProductReq struct {
	ProductId int64
}

type DeleteProductResp struct {
	ProductId int64
}

type GetInventoryReq struct {
	ProductId int32
}

type GetInventoryResp struct {
	ProductId int32
	Stock     int32
}

type GetProductDetailReq struct {
	ProductId int64
}

type GetProductDetailResp struct {
	Product Product
}

type GetProductsReq struct {
	Page     int32
	PageSize int32
}

type GetProductsResp struct {
	Products []Product
	Total    int32
}

type SemanticSearchReq struct {
	Query string
}

type SemanticSearchResp struct {
	Products []Product
}

type UpdateProductReq struct {
	ProductId   int64
	Name        string
	Description string
	Price       float64
	Stock       int32
}

type UpdateProductResp struct {
	ProductId int64
}
