// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types


type GetProfileReq struct {
	UserId int64
}

type LoginReq struct {
	Email    string
	Password string
}

type LoginResp struct {
	AccessToken string
	ExpireAt    string
}

type RegisterReq struct {
	Email    string
	Password string
	Nickname string
}

type UpdateProfileReq struct {
	UserId   int64
	Nickname string
}

type UserProfile struct {
	UserId    string
	Email     string
	Nickname  string
	CreatedAt string
}
