// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CancelOrderReq struct {
	OrderId int32
}

type CheckOutOrderReq struct {
	OrderId int32
}

type CommonResp struct {
	Code int32
	Msg  string
}

type GetOrderDetailReq struct {
	OrderId int32
}

type GetOrderDetailResp struct {
	Order Order
}

type GetOrderListResp struct {
	Orders []OrderProfile
}

type PlaceOrderReq struct {
	Items []OrderItem
}

type PlaceOrderResp struct {
	OrderId int32
}

type UpdateOrderStatusReq struct {
	OrderId int32
	Status  string
}
