// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Cart struct {
	UserId     int64
	Items      []CartItem
	TotalPrice float64
}

type CartItem struct {
	ProductId   int64
	ProductName string
	Price       float64
	Quantity    int32
}

type Order struct {
	OrderId     int32
	UserId      int32
	Items       []OrderItem
	TotalAmount float64
	Status      string // e.g. Pending, Completed, Cancelled, Shipped
	CreateAt    string
	UpdateAt    string
}

type OrderItem struct {
	ProductId   int32
	ProductName string
	Price       float64
	Quantity    int32
}

type OrderProfile struct {
	OrderId     int32
	UserId      int32
	Status      string
	ProductName []string
	TotalAmount float64
}

type Product struct {
	ProductId   int64
	Name        string
	Description string
	Price       float64
	Stock       int32
}
