// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: ordering.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=productName,proto3" json:"productName,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_ordering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateAt      string                 `protobuf:"bytes,6,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt      string                 `protobuf:"bytes,7,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_ordering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *Order) GetUpdateAt() string {
	if x != nil {
		return x.UpdateAt
	}
	return ""
}

type OrderProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProductName   []string               `protobuf:"bytes,5,rep,name=productName,proto3" json:"productName,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,4,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderProfile) Reset() {
	*x = OrderProfile{}
	mi := &file_ordering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderProfile) ProtoMessage() {}

func (x *OrderProfile) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderProfile.ProtoReflect.Descriptor instead.
func (*OrderProfile) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{2}
}

func (x *OrderProfile) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderProfile) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderProfile) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderProfile) GetProductName() []string {
	if x != nil {
		return x.ProductName
	}
	return nil
}

func (x *OrderProfile) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type PlaceOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrderItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderReq) Reset() {
	*x = PlaceOrderReq{}
	mi := &file_ordering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderReq) ProtoMessage() {}

func (x *PlaceOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderReq.ProtoReflect.Descriptor instead.
func (*PlaceOrderReq) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceOrderReq) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PlaceOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResp) Reset() {
	*x = PlaceOrderResp{}
	mi := &file_ordering_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResp) ProtoMessage() {}

func (x *PlaceOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResp.ProtoReflect.Descriptor instead.
func (*PlaceOrderResp) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceOrderResp) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListReq) Reset() {
	*x = GetOrderListReq{}
	mi := &file_ordering_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListReq) ProtoMessage() {}

func (x *GetOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListReq.ProtoReflect.Descriptor instead.
func (*GetOrderListReq) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{5}
}

type GetOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderProfile        `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderListResp) Reset() {
	*x = GetOrderListResp{}
	mi := &file_ordering_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderListResp) ProtoMessage() {}

func (x *GetOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderListResp.ProtoReflect.Descriptor instead.
func (*GetOrderListResp) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderListResp) GetOrders() []*OrderProfile {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetOrderDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailReq) Reset() {
	*x = GetOrderDetailReq{}
	mi := &file_ordering_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailReq) ProtoMessage() {}

func (x *GetOrderDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailReq.ProtoReflect.Descriptor instead.
func (*GetOrderDetailReq) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderDetailReq) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderDetailResp) Reset() {
	*x = GetOrderDetailResp{}
	mi := &file_ordering_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderDetailResp) ProtoMessage() {}

func (x *GetOrderDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderDetailResp.ProtoReflect.Descriptor instead.
func (*GetOrderDetailResp) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderDetailResp) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_ordering_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderReq) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type UpdateOrderStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusReq) Reset() {
	*x = UpdateOrderStatusReq{}
	mi := &file_ordering_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusReq) ProtoMessage() {}

func (x *UpdateOrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusReq) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateOrderStatusReq) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateOrderStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CheckOutOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOutOrderReq) Reset() {
	*x = CheckOutOrderReq{}
	mi := &file_ordering_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOutOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOutOrderReq) ProtoMessage() {}

func (x *CheckOutOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOutOrderReq.ProtoReflect.Descriptor instead.
func (*CheckOutOrderReq) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{11}
}

func (x *CheckOutOrderReq) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CommonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResp) Reset() {
	*x = CommonResp{}
	mi := &file_ordering_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResp) ProtoMessage() {}

func (x *CommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResp.ProtoReflect.Descriptor instead.
func (*CommonResp) Descriptor() ([]byte, []int) {
	return file_ordering_proto_rawDescGZIP(), []int{12}
}

func (x *CommonResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CommonResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_ordering_proto protoreflect.FileDescriptor

const file_ordering_proto_rawDesc = "" +
	"\n" +
	"\x0eordering.proto\x12\x05order\"}\n" +
	"\tOrderItem\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x05R\tproductId\x12 \n" +
	"\vproductName\x18\x02 \x01(\tR\vproductName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"\xd3\x01\n" +
	"\x05Order\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.order.OrderItemR\x05items\x12 \n" +
	"\vtotalAmount\x18\x04 \x01(\x01R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1a\n" +
	"\bcreateAt\x18\x06 \x01(\tR\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\a \x01(\tR\bupdateAt\"\x9c\x01\n" +
	"\fOrderProfile\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vproductName\x18\x05 \x03(\tR\vproductName\x12 \n" +
	"\vtotalAmount\x18\x04 \x01(\x01R\vtotalAmount\"7\n" +
	"\rPlaceOrderReq\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.order.OrderItemR\x05items\"*\n" +
	"\x0ePlaceOrderResp\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\"\x11\n" +
	"\x0fGetOrderListReq\"?\n" +
	"\x10GetOrderListResp\x12+\n" +
	"\x06orders\x18\x01 \x03(\v2\x13.order.OrderProfileR\x06orders\"-\n" +
	"\x11GetOrderDetailReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\"8\n" +
	"\x12GetOrderDetailResp\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"*\n" +
	"\x0eCancelOrderReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\"H\n" +
	"\x14UpdateOrderStatusReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\",\n" +
	"\x10CheckOutOrderReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x05R\aorderId\"2\n" +
	"\n" +
	"CommonResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\x88\x03\n" +
	"\bOrdering\x129\n" +
	"\n" +
	"PlaceOrder\x12\x14.order.PlaceOrderReq\x1a\x15.order.PlaceOrderResp\x12?\n" +
	"\fGetOrderList\x12\x16.order.GetOrderListReq\x1a\x17.order.GetOrderListResp\x12E\n" +
	"\x0eGetOrderDetail\x12\x18.order.GetOrderDetailReq\x1a\x19.order.GetOrderDetailResp\x127\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x11.order.CommonResp\x12C\n" +
	"\x11UpdateOrderStatus\x12\x1b.order.UpdateOrderStatusReq\x1a\x11.order.CommonResp\x12;\n" +
	"\rCheckOutOrder\x12\x17.order.CheckOutOrderReq\x1a\x11.order.CommonRespB\tZ\a./orderb\x06proto3"

var (
	file_ordering_proto_rawDescOnce sync.Once
	file_ordering_proto_rawDescData []byte
)

func file_ordering_proto_rawDescGZIP() []byte {
	file_ordering_proto_rawDescOnce.Do(func() {
		file_ordering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ordering_proto_rawDesc), len(file_ordering_proto_rawDesc)))
	})
	return file_ordering_proto_rawDescData
}

var file_ordering_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_ordering_proto_goTypes = []any{
	(*OrderItem)(nil),            // 0: order.OrderItem
	(*Order)(nil),                // 1: order.Order
	(*OrderProfile)(nil),         // 2: order.OrderProfile
	(*PlaceOrderReq)(nil),        // 3: order.PlaceOrderReq
	(*PlaceOrderResp)(nil),       // 4: order.PlaceOrderResp
	(*GetOrderListReq)(nil),      // 5: order.GetOrderListReq
	(*GetOrderListResp)(nil),     // 6: order.GetOrderListResp
	(*GetOrderDetailReq)(nil),    // 7: order.GetOrderDetailReq
	(*GetOrderDetailResp)(nil),   // 8: order.GetOrderDetailResp
	(*CancelOrderReq)(nil),       // 9: order.CancelOrderReq
	(*UpdateOrderStatusReq)(nil), // 10: order.UpdateOrderStatusReq
	(*CheckOutOrderReq)(nil),     // 11: order.CheckOutOrderReq
	(*CommonResp)(nil),           // 12: order.CommonResp
}
var file_ordering_proto_depIdxs = []int32{
	0,  // 0: order.Order.items:type_name -> order.OrderItem
	0,  // 1: order.PlaceOrderReq.items:type_name -> order.OrderItem
	2,  // 2: order.GetOrderListResp.orders:type_name -> order.OrderProfile
	1,  // 3: order.GetOrderDetailResp.order:type_name -> order.Order
	3,  // 4: order.Ordering.PlaceOrder:input_type -> order.PlaceOrderReq
	5,  // 5: order.Ordering.GetOrderList:input_type -> order.GetOrderListReq
	7,  // 6: order.Ordering.GetOrderDetail:input_type -> order.GetOrderDetailReq
	9,  // 7: order.Ordering.CancelOrder:input_type -> order.CancelOrderReq
	10, // 8: order.Ordering.UpdateOrderStatus:input_type -> order.UpdateOrderStatusReq
	11, // 9: order.Ordering.CheckOutOrder:input_type -> order.CheckOutOrderReq
	4,  // 10: order.Ordering.PlaceOrder:output_type -> order.PlaceOrderResp
	6,  // 11: order.Ordering.GetOrderList:output_type -> order.GetOrderListResp
	8,  // 12: order.Ordering.GetOrderDetail:output_type -> order.GetOrderDetailResp
	12, // 13: order.Ordering.CancelOrder:output_type -> order.CommonResp
	12, // 14: order.Ordering.UpdateOrderStatus:output_type -> order.CommonResp
	12, // 15: order.Ordering.CheckOutOrder:output_type -> order.CommonResp
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ordering_proto_init() }
func file_ordering_proto_init() {
	if File_ordering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordering_proto_rawDesc), len(file_ordering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordering_proto_goTypes,
		DependencyIndexes: file_ordering_proto_depIdxs,
		MessageInfos:      file_ordering_proto_msgTypes,
	}.Build()
	File_ordering_proto = out.File
	file_ordering_proto_goTypes = nil
	file_ordering_proto_depIdxs = nil
}
